# Generated by Django 4.0 on 2022-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
